apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
spec:
  selector:
    app: my-mongodb
  ports:
    - protocol: TCP
      port: 27017        # Internal port
      targetPort: 27017  # Container port
      nodePort: 30100   # External port (accessible via Minikube) # exports it to outside the cluster
  type: NodePort       # Expose via NodePort
