apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redpanda-data
  labels:
    app: redpanda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Omit storageClassName to use cluster default (e.g. standard on Minikube)
